# Generated by Django 3.1.2 on 2021-01-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=20)),
                ('userPass', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
