# Generated by Django 3.1.2 on 2021-01-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userEmail',
            field=models.CharField(default='NaN', max_length=50),
        ),
    ]
