# Generated by Django 3.1.2 on 2021-01-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMapp', '0002_user_useremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=20)),
                ('siteName', models.CharField(max_length=50)),
                ('sitePass', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Password',
            },
        ),
    ]
