# Generated by Django 3.1.2 on 2021-01-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMapp', '0003_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPass',
            field=models.BinaryField(),
        ),
    ]
