# Generated by Django 3.1.2 on 2021-01-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMapp', '0004_auto_20210106_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPass',
            field=models.CharField(max_length=15),
        ),
    ]
