# Generated by Django 3.1.2 on 2021-01-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMapp', '0005_auto_20210106_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPass',
            field=models.BinaryField(max_length=15),
        ),
    ]
