# Generated by Django 3.1.2 on 2021-01-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMapp', '0006_auto_20210106_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPass',
            field=models.CharField(max_length=50),
        ),
    ]
