# Generated by Django 3.1.2 on 2021-01-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMapp', '0007_auto_20210107_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPass',
            field=models.BinaryField(max_length=50),
        ),
    ]
