# Generated by Django 3.1.2 on 2021-01-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMapp', '0008_auto_20210107_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPass',
            field=models.BinaryField(editable=True, max_length=50),
        ),
    ]
