# Generated by Django 3.1.2 on 2021-01-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMapp', '0009_auto_20210107_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='sitePass',
            field=models.BinaryField(editable=True, max_length=50),
        ),
    ]
